# Generated by Django 5.0.3 on 2024-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort', models.CharField(max_length=100)),
                ('prf', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('l', models.CharField(max_length=100)),
                ('additional', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('product_availability', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pricelist',
            },
        ),
    ]
