# Generated by Django 5.0.3 on 2024-03-04 21:21

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_uploadrequisites_uploadrequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpricelist',
            name='file',
            field=models.FileField(error_messages='Only xlsx files!', upload_to='fileStorage/', validators=[main.models.validate_file_extension]),
        ),
    ]
